version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - 8000:80
  php-fpm:
    image: maxence/website-formation
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: maxence
      POSTGRES_PASSWORD: example
      POSTGRES_DB: formation
    ports:
      - 5432:5432